#pragma once
#include <JAGL.h>

#define COLOR_CHANNEL_ADD(value, amount) (((value) + (amount) > 255) ? 255 : ((value) + (amount)))
#define COLOR_RGB_ADD(r, g, b, a, amount) COLOR(COLOR_CHANNEL_ADD(r, amount), COLOR_CHANNEL_ADD(g, amount), COLOR_CHANNEL_ADD(b, amount), a)
#define COLOR_SELECT_FROM(r, g, b, a) COLOR_RGB_ADD(r, g, b, a, 25)
#define COLOR_PRESS_FROM(r, g, b, a) COLOR_RGB_ADD(r, g, b, a, 50)
#define COLOR_FROM_RGBA(rgba) COLOR(rgba)
#define COLOR_SELECT_FROM_RGBA(rgba) COLOR_SELECT_FROM(rgba)
#define COLOR_PRESS_FROM_RGBA(rgba) COLOR_PRESS_FROM(rgba)

#define COLOR_WHITE_RGBA 255, 255, 255, 255
#define COLOR_BLACK_RGBA 0, 0, 0, 255
#define COLOR_RED_RGBA 255, 0, 0, 255

#define COLOR_PRIMARY_RGBA 0, 155, 105, 255
#define COLOR_SECONDARY_RGBA 231, 18, 178, 255
#define COLOR_AVERAGE_RGBA 95, 94, 255, 255
#define COLOR_CURSOR_RGBA 77, 77, 77, 255
#define COLOR_SURFACE_RGBA 18, 18, 18, 255
#define COLOR_TOPBAR_RGBA 39, 39, 39, 255
#define COLOR_SUBBAR_RGBA 50, 50, 50, 255
#define COLOR_MAIN_TOPBAR_RGBA 39, 39, 39, 200
#define COLOR_TRANSPARENT_RGBA 0, 0, 0, 0

#define COLOR_WHITE COLOR_FROM_RGBA(COLOR_WHITE_RGBA)
#define COLOR_BLACK COLOR_FROM_RGBA(COLOR_BLACK_RGBA)
#define COLOR_RED COLOR_FROM_RGBA(COLOR_RED_RGBA)

#define COLOR_PRIMARY COLOR_FROM_RGBA(COLOR_PRIMARY_RGBA)
#define COLOR_SECONDARY COLOR_FROM_RGBA(COLOR_SECONDARY_RGBA)
#define COLOR_AVERAGE COLOR_FROM_RGBA(COLOR_AVERAGE_RGBA)
#define COLOR_CURSOR COLOR_FROM_RGBA(COLOR_CURSOR_RGBA)
#define COLOR_CURSORPRESS COLOR_PRESS_FROM_RGBA(COLOR_CURSOR_RGBA)

#define COLOR_MAINBG COLOR_FROM_RGBA(COLOR_SURFACE_RGBA)
#define COLOR_TOPBAR COLOR_FROM_RGBA(COLOR_TOPBAR_RGBA)
#define COLOR_SUBBAR COLOR_FROM_RGBA(COLOR_SUBBAR_RGBA)
#define COLOR_MAIN_TOPBAR COLOR_FROM_RGBA(COLOR_MAIN_TOPBAR_RGBA)
#define COLOR_MAIN_TOPBARBUTTONS COLOR_FROM_RGBA(COLOR_TRANSPARENT_RGBA)

#define COLOR_MAIN_TOPBAR_PACK COLOR_SECONDARY
#define COLOR_MAIN_TOPBAR_THEME COLOR_PRIMARY
#define COLOR_TOPBARCURSOR COLOR_CURSOR

#define COLOR_SCROLLBARBG COLOR_MAIN_TOPBAR
#define COLOR_SCROLLBAR COLOR_TOPBAR
#define COLOR_SCROLLBARTHUMB COLOR_SECONDARY

#define COLOR_CARDCURSOR COLOR_PRIMARY
#define COLOR_CARDCURSORPRESS COLOR_PRESS_FROM_RGBA(COLOR_PRIMARY_RGBA)

#define COLOR_BUTTONBACK COLOR_RED

#define COLOR_DOWNLOADBTN COLOR_PRIMARY
#define COLOR_DOWNLOADBTNSEL COLOR_SELECT_FROM_RGBA(COLOR_PRIMARY_RGBA)
#define COLOR_DOWNLOADBTNPRS COLOR_PRESS_FROM_RGBA(COLOR_PRIMARY_RGBA)

#define COLOR_INSTALLBTN COLOR_SECONDARY
#define COLOR_INSTALLBTNSEL COLOR_SELECT_FROM_RGBA(COLOR_SECONDARY_RGBA)
#define COLOR_INSTALLBTNPRS COLOR_PRESS_FROM_RGBA(COLOR_SECONDARY_RGBA)

#define COLOR_INSTALLONLYBTN COLOR_AVERAGE
#define COLOR_INSTALLONLYBTNSEL COLOR_SELECT_FROM_RGBA(COLOR_AVERAGE_RGBA)
#define COLOR_INSTALLONLYBTNPRS COLOR_PRESS_FROM_RGBA(COLOR_AVERAGE_RGBA)

#define COLOR_FILTERACTIVE COLOR_SECONDARY

#define COLOR_GREY COLOR(66, 66, 68, 255)
#define COLOR_LIGHTGREY COLOR(100, 100, 100, 255)
#define COLOR_VERYLIGHTGREY_RGBA COLOR(190, 190, 190, 255)
#define COLOR_AQUA COLOR(0, 203, 255, 255)
#define COLOR_BLUEGREY COLOR(50, 80, 100, 255)
#define COLOR_DARKGREY COLOR(57, 57, 59, 255)
#define COLOR_DARKERGREY COLOR(42, 42, 42, 255)
#define COLOR_LESSBLUEGREY COLOR(55, 58, 62, 255)
#define COLOR_MAGENTA COLOR(170, 0, 105, 255)
#define COLOR_GREYMAGENTA COLOR(99, 55, 90, 255)
#define COLOR_DARKERRED COLOR(63, 0, 0, 255)
#define COLOR_DARKRED COLOR(100, 0, 0, 255)
#define COLOR_DARKERORANGE COLOR(114, 86, 0, 255)
#define COLOR_DARKORANGE COLOR(142, 99, 0, 255)
#define COLOR_DARKERBLUE COLOR(0, 52, 61, 255)
#define COLOR_DARKBLUE COLOR(0, 86, 99, 255)
